version: '3.9'

services:
  web:
    build: .
    container_name: rag_flask
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PG_HOST=host.docker.internal
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma
    container_name: rag_chroma
    volumes:
      - chroma_data:/chroma/chroma
      - .:/app  # 把本機專案目錄 mount 到容器內
    ports:
      - "8000:8000"

volumes:
  chroma_data:
